window.__ModuleLoader__.load({
  id: "dsh-turn-status-phrases",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    var React = require("react");
    var h = React.createElement;

    // BUILTIN_LIBRARIES_START: generated by npm run build
    var BUILTIN = {
      "chinese-mythology": {
        "name": "中国神话",
        "phrases": [
          "嫦娥奔月",
          "精卫填海",
          "夸父逐日",
          "后羿射日",
          "女娲补天",
          "盘古开天",
          "愚公移山",
          "大禹治水",
          "牛郎织女",
          "哪吒闹海",
          "八仙过海",
          "白蛇传说",
          "封神演义",
          "鲧禹治水",
          "仓颉造字"
        ]
      },
      "claude-code": {
        "name": "Claude Code",
        "phrases": [
          "Accomplishing",
          "Actioning",
          "Actualizing",
          "Architecting",
          "Baking",
          "Beaming",
          "Beboppin'",
          "Befuddling",
          "Billowing",
          "Blanching",
          "Bloviating",
          "Boogieing",
          "Boondoggling",
          "Booping",
          "Bootstrapping",
          "Brewing",
          "Bunning",
          "Burrowing",
          "Calculating",
          "Canoodling",
          "Caramelizing",
          "Cascading",
          "Catapulting",
          "Cerebrating",
          "Channeling",
          "Channelling",
          "Choreographing",
          "Churning",
          "Clauding",
          "Coalescing",
          "Cogitating",
          "Combobulating",
          "Composing",
          "Computing",
          "Concocting",
          "Considering",
          "Contemplating",
          "Cooking",
          "Crafting",
          "Creating",
          "Crunching",
          "Crystallizing",
          "Cultivating",
          "Deciphering",
          "Deliberating",
          "Determining",
          "Dilly-dallying",
          "Discombobulating",
          "Doing",
          "Doodling",
          "Drizzling",
          "Ebbing",
          "Effecting",
          "Elucidating",
          "Embellishing",
          "Enchanting",
          "Envisioning",
          "Evaporating",
          "Fermenting",
          "Fiddle-faddling",
          "Finagling",
          "Flambéing",
          "Flibbertigibbeting",
          "Flowing",
          "Flummoxing",
          "Fluttering",
          "Forging",
          "Forming",
          "Frolicking",
          "Frosting",
          "Gallivanting",
          "Galloping",
          "Garnishing",
          "Generating",
          "Germinating",
          "Gesticulating",
          "Gitifying",
          "Grooving",
          "Gusting",
          "Harmonizing",
          "Hashing",
          "Hatching",
          "Herding",
          "Honking",
          "Hullaballooing",
          "Hyperspacing",
          "Ideating",
          "Imagining",
          "Improvising",
          "Incubating",
          "Inferring",
          "Infusing",
          "Ionizing",
          "Jitterbugging",
          "Julienning",
          "Kneading",
          "Leavening",
          "Levitating",
          "Lollygagging",
          "Manifesting",
          "Marinating",
          "Meandering",
          "Metamorphosing",
          "Misting",
          "Moonwalking",
          "Moseying",
          "Mulling",
          "Musing",
          "Mustering",
          "Nebulizing",
          "Nesting",
          "Newspapering",
          "Noodling",
          "Nucleating",
          "Orbiting",
          "Orchestrating",
          "Osmosing",
          "Perambulating",
          "Percolating",
          "Perusing",
          "Philosophising",
          "Photosynthesizing",
          "Pollinating",
          "Pondering",
          "Pontificating",
          "Pouncing",
          "Precipitating",
          "Prestidigitating",
          "Processing",
          "Proofing",
          "Propagating",
          "Puttering",
          "Puzzling",
          "Quantumizing",
          "Razzle-dazzling",
          "Razzmatazzing",
          "Recombobulating",
          "Reticulating",
          "Roosting",
          "Ruminating",
          "Sautéing",
          "Scampering",
          "Schlepping",
          "Scurrying",
          "Seasoning",
          "Shenaniganing",
          "Shimmying",
          "Simmering",
          "Skedaddling",
          "Sketching",
          "Slithering",
          "Smooshing",
          "Sock-hopping",
          "Spelunking",
          "Spinning",
          "Sprouting",
          "Stewing",
          "Sublimating",
          "Swirling",
          "Swooping",
          "Symbioting",
          "Synthesizing",
          "Tempering",
          "Thinking",
          "Thundering",
          "Tinkering",
          "Tomfoolering",
          "Topsy-turvying",
          "Transfiguring",
          "Transmuting",
          "Twisting",
          "Undulating",
          "Unfurling",
          "Unravelling",
          "Vibing",
          "Waddling",
          "Wandering",
          "Warping",
          "Whatchamacalliting",
          "Whirlpooling",
          "Whirring",
          "Whisking",
          "Wibbling",
          "Working",
          "Wrangling",
          "Zesting",
          "Zigzagging"
        ]
      },
      "chinese-modal-words": {
        "name": "中文单字语气词",
        "phrases": [
          "啊",
          "哦",
          "噢",
          "喔",
          "呀",
          "啦",
          "噜",
          "嘞",
          "哟",
          "呦",
          "的",
          "了",
          "吗",
          "呢",
          "吧",
          "呵",
          "哈",
          "嘿",
          "唉",
          "哎",
          "耶",
          "咦",
          "欸",
          "呃",
          "欤",
          "罢",
          "呗",
          "啵",
          "嘛",
          "呐",
          "哩",
          "咧",
          "咯",
          "啰",
          "喽",
          "哪",
          "嗯",
          "哼",
          "呸",
          "啧",
          "噻",
          "哉",
          "兮",
          "家",
          "来",
          "唻",
          "嚜"
        ]
      },
      "classical-chinese-interjections": {
        "name": "文言文感叹词",
        "phrases": [
          "呜呼",
          "噫吁嚱",
          "嗟乎",
          "嗟夫",
          "悲夫",
          "休矣",
          "已矣",
          "善哉",
          "异哉",
          "快哉",
          "惜哉",
          "嘻",
          "噫",
          "吁",
          "诺",
          "唯",
          "猗欤",
          "於戏",
          "乌乎",
          "噫嘻",
          "呜呼哀哉",
          "於乎",
          "嗟嗟",
          "噫乎",
          "猗嗟",
          "休哉",
          "已乎",
          "哀哉",
          "痛哉",
          "惜乎"
        ]
      },
      "journey-to-the-west": {
        "name": "西游记",
        "phrases": [
          "大闹天宫",
          "齐天大圣",
          "西天取经",
          "火眼金睛",
          "腾云驾雾",
          "来去无踪",
          "大显神通",
          "千变万化",
          "明察秋毫",
          "除恶务尽",
          "天下太平",
          "不避艰险",
          "翻江倒海",
          "降妖除魔",
          "七十二变",
          "筋斗云",
          "金箍棒",
          "花果山",
          "水帘洞",
          "五行山",
          "无底洞",
          "白骨精",
          "牛魔王",
          "铁扇公主",
          "红孩儿",
          "三打白骨精",
          "真假美猴王",
          "三借芭蕉扇",
          "大战红孩儿",
          "偷吃蟠桃",
          "偷盗金丹",
          "搅乱蟠桃宴",
          "打出南天门",
          "自封齐天大圣",
          "被压五行山",
          "踏上取经路",
          "九九八十一难",
          "取得真经",
          "修成正果",
          "斗战胜佛"
        ]
      },
      "romance-of-the-three-kingdoms": {
        "name": "三国演义",
        "phrases": [
          "大丈夫生居天地间，岂能郁郁久居人下",
          "宁教我负天下人，休教天下人负我",
          "天下大事，分久必合，合久必分",
          "淡泊以明志，宁静而致远",
          "鞠躬尽瘁，死而后已",
          "既生瑜，何生亮",
          "此间乐，不思蜀",
          "良禽择木而栖，贤臣择主而事",
          "夫英雄者，胸怀大志，腹有良谋",
          "今天下英雄，惟使君与操耳",
          "箭在弦上，不得不发",
          "玉可碎而不可改其白，竹可焚而不可毁其节",
          "周郎妙计安天下，赔了夫人又折兵",
          "我从未见过如此厚颜无耻之徒",
          "谋事在人，成事在天",
          "三军易得，一将难求",
          "良药苦口利于病，忠言逆耳利于行",
          "勿以恶小而为之，勿以善小而不为",
          "举大事者必以人为本",
          "子龙一身都是胆也",
          "人中吕布，马中赤兔",
          "大丈夫生于乱世，当带三尺剑立不世之功",
          "竖子不足与谋",
          "龙困浅滩遭虾戏，虎落平阳被犬欺",
          "志当存高远",
          "非学无以广才，非志无以成学",
          "不傲才以骄人，不以宠而作威",
          "为人者，有大度成大器矣",
          "马逢伯乐而嘶，人遇知己而死",
          "破巢之下，安有完卵乎",
          "兵不在多，在于精，将不在勇，在于谋",
          "扬汤止沸，不如去薪",
          "强中自有强中手，用诈还逢识诈人",
          "胜负兵家之常，何可自隳其志",
          "生得其名，死得其所",
          "万事俱备，只欠东风",
          "大丈夫处世，不能立功建业，几与草木同腐乎",
          "吾乃常山赵子龙也，谁敢于我决一死战",
          "三性家奴休走，燕人张翼德在此",
          "臣等正欲死战，陛下何故先降",
          "君疑臣则臣必死",
          "智者务其实，愚者争虚名"
        ]
      },
      "niulai-meme": {
        "name": "牛来梗",
        "phrases": [
          "牛来",
          "羊来",
          "鸡来",
          "猪来",
          "狗来",
          "猫来",
          "马来",
          "龙来",
          "虎来",
          "兔来",
          "蛇来",
          "鼠来",
          "猴来",
          "鸟来",
          "鱼来",
          "虫来",
          "风来",
          "雨来",
          "雪来",
          "雷来",
          "电来",
          "你来",
          "我来",
          "他来",
          "她来",
          "都来",
          "福来",
          "财来",
          "运来",
          "喜来",
          "春来",
          "夏来",
          "秋来",
          "冬来",
          "潮来",
          "浪来",
          "云来",
          "雾来",
          "霜来",
          "天来",
          "地来",
          "人来",
          "神来",
          "鬼来",
          "花来",
          "草来",
          "树来",
          "山来",
          "水来",
          "日来",
          "月来",
          "星来",
          "光来",
          "暗来"
        ]
      },
      "china-slogans": {
        "name": "中国国家标语",
        "phrases": [
          "富强",
          "民主",
          "文明",
          "和谐",
          "自由",
          "平等",
          "公正",
          "法治",
          "爱国",
          "敬业",
          "诚信",
          "友善",
          "依法治国",
          "一国两制",
          "改革开放",
          "中华民族伟大复兴",
          "中国梦",
          "中国式现代化",
          "三个代表",
          "科学发展观",
          "和谐社会",
          "精神文明建设",
          "物质文明建设",
          "政治文明建设",
          "以热爱祖国为荣",
          "以服务人民为荣",
          "以崇尚科学为荣",
          "以辛勤劳动为荣",
          "以团结互助为荣",
          "以诚实守信为荣",
          "以遵纪守法为荣",
          "以艰苦奋斗为荣",
          "全面深化改革",
          "全面依法治国",
          "全面从严治党",
          "创新",
          "协调",
          "绿色",
          "开放",
          "共享",
          "绿水青山就是金山银山",
          "人类命运共同体",
          "不忘初心",
          "牢记使命",
          "砥砺前行",
          "立党为公",
          "执政为民",
          "全心全意为人民服务",
          "权为民所用",
          "情为民所系",
          "利为民所谋",
          "群众利益无小事",
          "发展是硬道理",
          "小康社会",
          "共同富裕",
          "人民至上",
          "西部大开发",
          "一带一路",
          "京津冀协同发展",
          "长江经济带",
          "粤港澳大湾区",
          "长三角一体化",
          "乡村振兴",
          "新型城镇化",
          "区域协调发展",
          "科教兴国",
          "人才强国",
          "创新驱动发展"
        ]
      }
    };
    // BUILTIN_LIBRARIES_END
    // 本地配置存储键
    var STORAGE = "dsh-turn-status-phrases:v1";
    // 默认词库 id
    var DEFAULT_ID = "chinese-mythology";
    // locale 字典命名空间
    var NS = "turn-status-phrases";
    // 内置词库 id 到字典 key 的映射，用于让内置词库显示名跟随界面语言
    var BUILTIN_NAME_KEYS = {
      "chinese-mythology": "builtinChineseMythology",
      "claude-code": "builtinClaudeCode"
    };
    // 中文字典，key 集合以此为准
    var DICT_ZH = {
      title: "轮次状态短语",
      description: "模型或智能体工作期间显示不断变化的状态短语。配置仅保存在当前浏览器。",
      enable: "启用动态短语",
      library: "当前词库",
      count: "词条数：{n}",
      contents: "词库内容（每行一条）",
      add: "新建词库",
      remove: "删除当前词库",
      createComingSoon: "自定义词库编辑功能正在开发中，敬请期待。",
      builtinChineseMythology: "中国神话",
      builtinClaudeCode: "Claude Code",
      strategy: "轮换策略",
      strategySequential: "顺序轮换",
      strategyRandom: "随机轮换",
      strategyWeighted: "首行优先随机轮换"
    };
    // 英文字典，key 集合与 DICT_ZH 完全一致
    var DICT_EN = {
      title: "Turn Status Phrases",
      description: "Show rotating status phrases while the model or agent is working. Settings are stored in this browser only.",
      enable: "Enable rotating phrases",
      library: "Current library",
      count: "Phrases: {n}",
      contents: "Library contents (one phrase per line)",
      add: "New library",
      remove: "Delete current library",
      createComingSoon: "Custom library editing is coming soon.",
      builtinChineseMythology: "Chinese Mythology",
      builtinClaudeCode: "Claude Code",
      strategy: "Rotation strategy",
      strategySequential: "Sequential",
      strategyRandom: "Random",
      strategyWeighted: "First-priority weighted"
    };
    // DSH 原始状态文案的正文部分（不含省略号）
    var ORIGINAL_LABEL = "Deep diving";
    // 状态文案统一拼接的省略号后缀，与 DSH 原生显示保持一致
    var SUFFIX = "...";
    // DSH 原始状态文案，停用或卸载时用于还原
    var ORIGINAL_TEXT = ORIGINAL_LABEL + SUFFIX;
    // turnStatus 容器选择器。类名由 CSS module 生成，带哈希前缀（如 Md3f7G_turnStatus），
    // 因此用 role 与类名包含匹配联合定位，不依赖具体哈希
    var TARGET_SELECTOR = 'div[role="status"][class*="turnStatus"]';
    // 原始文案匹配，允许结尾省略号存在或缺失
    var ORIGINAL_PATTERN = /Deep diving(?:\.\.\.)?/;
    // DOM 变更触发的接管扫描节流间隔（毫秒）
    var CAPTURE_DELAY = 150;
    // 轮换策略枚举
    var STRATEGY_SEQUENTIAL = "sequential";
    var STRATEGY_RANDOM = "random";
    var STRATEGY_WEIGHTED = "weighted";
    var DEFAULT_STRATEGY = STRATEGY_RANDOM;

    // 根据 UTF-8 字节长度计算显示时间，并限制在1.8到8秒之间
    function getDisplayDuration(text) {
      var MIN_DURATION = 1800;  // 最短1.8秒
      var MS_PER_BYTE = 100;    // 每个字节100毫秒
      var MAX_DURATION = 8000;  // 最长8秒上限
      var byteLength = new TextEncoder().encode(text).length;
      var duration = byteLength * MS_PER_BYTE;
      return Math.min(Math.max(duration, MIN_DURATION), MAX_DURATION);
    }

    // Keep the settings section aligned with DSH's native settings cards.
    var SETTINGS_CSS = ""+
      ".dshTspSection{width:100%;max-width:760px;color:var(--dsw-alias-label-primary);display:flex;flex-direction:column;gap:14px}"+
      ".dshTspCard{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:10px;overflow:hidden}"+
      ".dshTspHeader{display:flex;align-items:flex-start;gap:12px;padding:16px;border-bottom:1px solid var(--dsw-alias-border-l2)}"+
      ".dshTspHeaderText{display:flex;flex-direction:column;gap:4px;min-width:0}"+
      ".dshTspTitle{font-size:15px;font-weight:600;line-height:20px}"+
      ".dshTspDescription,.dshTspHint{margin:0;color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:20px}"+
      ".dshTspBody{display:flex;flex-direction:column;gap:18px;padding:16px}"+
      ".dshTspField{display:flex;flex-direction:column;gap:7px}"+
      ".dshTspLabel{font-size:13px;font-weight:600;line-height:20px}"+
      ".dshTspSelect{width:100%;max-width:420px;height:36px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit;padding:0 10px;outline:none}"+
      ".dshTspSelect:focus-visible{border-color:var(--dsw-alias-state-business-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-state-business-primary) 18%,transparent)}"+
      ".dshTspToggle{display:flex;align-items:center;gap:10px;min-height:24px;cursor:pointer;font-size:13px}"+
      ".dshTspToggle input{width:16px;height:16px;margin:0;accent-color:var(--dsw-alias-state-business-primary)}"+
      ".dshTspCount{margin:0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}"+
      ".dshTspContents{display:flex;flex-direction:column;gap:7px}"+
      ".dshTspTextarea{box-sizing:border-box;width:100%;min-height:180px;resize:vertical;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:13px/20px var(--dsw-font-family);padding:9px 10px;outline:none;white-space:pre;overflow:auto}"+
      ".dshTspTextarea:focus-visible{border-color:var(--dsw-alias-state-business-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-state-business-primary) 18%,transparent)}"+
      ".dshTspTextarea::selection{background:var(--dsw-alias-state-business-primary);color:#fff}"+
      ".dshTspActions{display:flex;flex-wrap:wrap;gap:8px;padding-top:2px}"+
      ".dshTspButton{height:32px;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit;font-size:13px;padding:0 12px;cursor:pointer}"+
      ".dshTspButton:hover{background:var(--dsw-alias-bg-layer-2);border-color:var(--dsw-alias-label-dimmed)}"+
      ".dshTspButtonPrimary{background:var(--dsw-alias-state-business-primary);border-color:var(--dsw-alias-state-business-primary);color:#fff}"+
      ".dshTspButtonPrimary:hover{filter:brightness(1.05)}"+
      ".dshTspButtonDanger{color:var(--dsw-alias-state-error-primary)}";
    // 原生渐变附着在状态容器或其伪元素上，统一使用当前轮次的动态时长。
    var STATUS_ANIMATION_CSS = TARGET_SELECTOR + "[data-dsh-tsp-animation]{animation-duration:var(--dsh-tsp-duration)!important}" +
      TARGET_SELECTOR + "[data-dsh-tsp-animation]::before{animation-duration:var(--dsh-tsp-duration)!important}" +
      TARGET_SELECTOR + "[data-dsh-tsp-animation]::after{animation-duration:var(--dsh-tsp-duration)!important}";
      var STATUS_ANIMATION_RESET_CSS = TARGET_SELECTOR + "[data-dsh-tsp-animation-reset]{animation:none!important}" +
        TARGET_SELECTOR + "[data-dsh-tsp-animation-reset]::before{animation:none!important}" +
        TARGET_SELECTOR + "[data-dsh-tsp-animation-reset]::after{animation:none!important}";

    function installSettingsStyles() {
      if (document.querySelector("style[data-dsh-turn-status-phrases]") !== null) return;
      var tag = document.createElement("style");
      tag.dataset.dshTurnStatusPhrases = "true";
      tag.textContent = SETTINGS_CSS + STATUS_ANIMATION_CSS + STATUS_ANIMATION_RESET_CSS;
      document.head.appendChild(tag);
    }

    var state = {
      enabled: true, // 是否启用动态短语
      libraryId: DEFAULT_ID, // 当前生效的词库 id
      libraries: cloneBuiltin(), // 全部词库（内置 + 自定义）
      previous: "", // 上一次选中的短语，用于避免连续重复
      strategy: DEFAULT_STRATEGY, // 轮换策略
      sequenceIndex: 0, // 顺序轮换的当前索引
      timer: null, // 短语轮换定时器句柄
      currentPhrase: "", // 当前轮次展示的短语，确保显示内容和计时一致
      observer: null, // DOM 变更观察者
      targets: new Set(), // 已接管的 turnStatus 文本节点集合
      pendingCapture: false // 是否已排队一次接管扫描，用于节流
    };

    /**
     * 深拷贝一份内置词库。
     * state.libraries 会被设置页直接增删，必须与常量 BUILTIN 隔离，避免污染。
     * @returns {Object} 内置词库副本
     */
    function cloneBuiltin() {
      var copy = {};
      Object.keys(BUILTIN).forEach(function (id) {
        copy[id] = { name: BUILTIN[id].name, phrases: BUILTIN[id].phrases.slice() };
      });
      return copy;
    }

    /**
     * 判断给定 id 是否为插件自带的内置词库。
     * 内置词库不允许删除，判断以常量 BUILTIN 为唯一依据，
     * 保证删除守卫与删除按钮的显示条件口径一致。
     * @param {string} id 词库 id
     * @returns {boolean} 是内置词库返回 true
     */
    function isBuiltin(id) {
      return Object.prototype.hasOwnProperty.call(BUILTIN, id);
    }

    /**
     * 用代码内的当前版本补齐 state.libraries 里全部内置词库，自定义词库原样保留。
     * 内置词库在设置页不可编辑也不可删除，localStorage 里的同名条目只是旧版本插件留下的快照，
     * 因此一律以 BUILTIN 为准，这样新增内置词库和后续内置词条的更新才能对老用户生效。
     * 写入的是 cloneBuiltin 的深拷贝，避免 state.libraries 直接引用常量 BUILTIN 被设置页污染。
     * @returns {void}
     */
    function restoreBuiltin() {
      var fresh = cloneBuiltin();
      Object.keys(fresh).forEach(function (id) {
        state.libraries[id] = fresh[id];
      });
    }

    /**
     * 校验并规整外部传入的词库集合，丢弃结构非法的条目。
     * @param {Object} value 待校验的词库集合
     * @returns {Object} 合法词库集合；全部非法时回退到内置词库副本
     */
    function normalizeLibraries(value) {
      var result = {};
      Object.keys(value || {}).forEach(function (id) {
        var item = value[id];
        if (!item || typeof item.name !== "string" || !Array.isArray(item.phrases)) return;
        var phrases = Array.from(new Set(item.phrases.filter(function (p) { return typeof p === "string" && p.trim(); })));
        if (phrases.length) result[id] = { name: item.name.trim(), phrases: phrases };
      });
      return Object.keys(result).length ? result : cloneBuiltin();
    }

    /**
     * 从 localStorage 读取配置并保证全部内置词库与当前选中项始终可用。
     * @returns {void}
     */
    function readState() {
      try {
        var saved = JSON.parse(localStorage.getItem(STORAGE) || "null");
        if (saved && typeof saved === "object") {
          state.enabled = saved.enabled !== false;
          state.libraryId = typeof saved.libraryId === "string" ? saved.libraryId : DEFAULT_ID;
          if (saved.libraries && typeof saved.libraries === "object") state.libraries = normalizeLibraries(saved.libraries);
          // 读取轮换策略，验证合法性
          if (typeof saved.strategy === "string" &&
              (saved.strategy === STRATEGY_SEQUENTIAL ||
               saved.strategy === STRATEGY_RANDOM ||
               saved.strategy === STRATEGY_WEIGHTED)) {
            state.strategy = saved.strategy;
          }
        }
      } catch (_) {}
      // 取短语与删除自定义词库都以默认词库为兜底，必须保证其存在。
      // persist 会把整个 state.libraries 写入 localStorage，老用户存下的快照里没有本次新增的内置词库，
      // 因此这里补齐的是全部内置词库而不只是默认词库，DEFAULT_ID 作为内置词库之一同样被覆盖
      restoreBuiltin();
      if (!state.libraries[state.libraryId]) state.libraryId = DEFAULT_ID;
    }

    /**
     * 将当前配置写入 localStorage。
     * @returns {void}
     */
    function persist() {
      try {
        localStorage.setItem(STORAGE, JSON.stringify({
          enabled: state.enabled,
          libraryId: state.libraryId,
          libraries: state.libraries,
          strategy: state.strategy
        }));
      } catch (_) {}
    }

    /**
     * 从当前词库根据轮换策略取一条短语。
     * 返回的是不含省略号的正文，省略号由 writePhrase 统一拼接。
     * @returns {string} 短语正文；词库为空时返回原始文案正文
     */
    function phrase() {
      var library = state.libraries[state.libraryId] || state.libraries[DEFAULT_ID];
      var list = (library && library.phrases) || [];
      if (!list.length) return ORIGINAL_LABEL;
      if (list.length === 1) return list[0];
      var next;
      if (state.strategy === STRATEGY_SEQUENTIAL) {
        // 顺序轮换：按词库顺序依次轮换
        next = list[state.sequenceIndex % list.length];
        state.sequenceIndex = (state.sequenceIndex + 1) % list.length;
      } else if (state.strategy === STRATEGY_WEIGHTED) {
        // 首行优先随机轮换：第一条短语权重为其他短语的5倍
        var totalWeight = list.length + 4; // 第一条权重5，其他权重1，总权重为 list.length + 4
        var random = Math.random() * totalWeight;
        if (random < 5) {
          next = list[0];
        } else {
          // 从剩余短语中随机选择
          var index = Math.floor((random - 5)) + 1;
          next = list[Math.min(index, list.length - 1)];
        }
      } else {
        // 随机轮换（默认）：随机选择短语，不与上一条相同
        var candidates = list.filter(function (item) { return item !== state.previous; });
        next = candidates[Math.floor(Math.random() * candidates.length)];
      }
      state.previous = next;
      return next;
    }

    /**
     * 定位 turnStatus 容器内承载状态文案的文本节点。
     * 容器结构为 [文本节点, 可选的计时 span]，因此只认第一个文本节点。
     * @param {Element} element turnStatus 容器元素
     * @returns {Text|null} 目标文本节点；不是状态文案时返回 null
     */
    function targetOf(element) {
      var children = element.childNodes;
      for (var i = 0; i < children.length; i++) {
        var node = children[i];
        if (node.nodeType !== Node.TEXT_NODE) continue;
        // 已接管的节点内容已是中文短语，只能靠节点身份识别；未接管的按原始文案匹配
        if (state.targets.has(node) || ORIGINAL_PATTERN.test(node.nodeValue || "")) return node;
        return null;
      }
      return null;
    }

    function setAnimationDuration(node, duration) {
      var element = node.parentElement;
      if (!element) return;
      element.dataset.dshTspAnimation = "true";
      element.style.setProperty("--dsh-tsp-duration", duration + "ms");
    }

    function restartAnimation(node, duration, update) {
      var element = node.parentElement;
      if (!element) {
        update();
        return;
      }
      setAnimationDuration(node, duration);
      element.dataset.dshTspAnimationReset = "true";
      // Commit animation:none, replace the text, then restore the native keyframes at progress zero.
      void element.offsetWidth;
      update();
      delete element.dataset.dshTspAnimationReset;
      void element.offsetWidth;
    }

    function clearAnimationDuration(node) {
      var element = node.parentElement;
      if (!element) return;
      delete element.dataset.dshTspAnimation;
      delete element.dataset.dshTspAnimationReset;
      element.style.removeProperty("--dsh-tsp-duration");
    }

    /**
     * 写入文本节点内容，短语后拼接省略号，与 DSH 原生显示保持一致。
     * 只改 nodeValue 而不动容器 textContent，这样既保留 React 持有的节点引用，
     * 也不会破坏 15 秒后追加的计时 span。
     * @param {Text} node 目标文本节点
     * @param {string} [text] 本轮展示的短语正文
     * @returns {void}
     */
    function writePhrase(node, text) {
      if (!state.enabled) {
        clearAnimationDuration(node);
        if (node.nodeValue !== ORIGINAL_TEXT) node.nodeValue = ORIGINAL_TEXT;
        return;
      }
      var value = text || state.currentPhrase;
      if (!value) {
        value = phrase();
        state.currentPhrase = value;
      }
      var duration = getDisplayDuration(value);
      var displayed = value + SUFFIX;
      if (node.nodeValue !== displayed) {
        restartAnimation(node, duration, function () { node.nodeValue = displayed; });
      } else {
        setAnimationDuration(node, duration);
      }
    }

    /**
     * 移除已从文档中卸载的文本节点，避免集合无限增长。
     * @returns {void}
     */
    function prune() {
      state.targets.forEach(function (node) {
        if (!node.isConnected) state.targets.delete(node);
      });
    }

    /**
     * 扫描文档并接管新出现的 turnStatus 文本节点，接管即刻替换文案。
     * @returns {void}
     */
    function capture() {
      var elements = document.querySelectorAll(TARGET_SELECTOR);
      for (var i = 0; i < elements.length; i++) {
        var node = targetOf(elements[i]);
        if (node === null || state.targets.has(node)) continue;
        state.targets.add(node);
        writePhrase(node);
      }
    }

    /**
     * 节流排队一次接管扫描，避免流式输出期间高频扫描 DOM。
     * @returns {void}
     */
    function scheduleCapture() {
      if (state.pendingCapture) return;
      state.pendingCapture = true;
      window.setTimeout(function () {
        state.pendingCapture = false;
        prune();
        capture();
      }, CAPTURE_DELAY);
    }

    /**
     * 立即刷新全部已接管节点的文案，用于定时轮换与设置项变更后同步。
     * @returns {void}
     */
    function refresh(text) {
      prune();
      if (state.enabled && !text) text = phrase();
      state.currentPhrase = text || "";
      capture();
      state.targets.forEach(function (node) { writePhrase(node, text); });
    }

    /**
     * 调度下一次轮换，根据当前文字长度动态计算等待时间。
     * @returns {void}
     */
    function scheduleNext() {
      if (!state.enabled || !state.observer) return;
      var text = phrase();
      var duration = getDisplayDuration(text);
      refresh(text);
      state.timer = window.setTimeout(function () {
        state.timer = null;
        scheduleNext();
      }, duration);
    }

    /**
     * 取消旧轮换并以当前配置开始新一轮，避免展示文字和旧等待时间不一致。
     * @returns {void}
     */
    function restartSchedule() {
      if (state.timer) clearTimeout(state.timer);
      state.timer = null;
      if (state.enabled && state.observer) scheduleNext();
      else refresh();
    }

    /**
     * 启动 DOM 观察与短语轮换。
     * 观察根取 documentElement，它在脚本执行时必然存在，无需等待 body。
     * @returns {void}
     */
    function start() {
      if (state.observer) return;
      state.observer = new MutationObserver(function (records) {
        for (var i = 0; i < records.length; i++) {
          var added = records[i].addedNodes;
          for (var j = 0; j < added.length; j++) {
            // 只有新增元素才可能带来新的 turnStatus 容器，文本变更交给轮换定时器处理
            if (added[j].nodeType === Node.ELEMENT_NODE) {
              scheduleCapture();
              return;
            }
          }
        }
      });
      state.observer.observe(document.documentElement, { childList: true, subtree: true });
      capture();
      scheduleNext();
    }

    /**
     * 停止观察与轮换，并把仍在文档中的节点还原为原始文案。
     * @returns {void}
     */
    function stop() {
      if (state.observer) state.observer.disconnect();
      state.observer = null;
      if (state.timer) clearTimeout(state.timer);
      state.timer = null;
      state.targets.forEach(function (node) {
        clearAnimationDuration(node);
        if (node.isConnected && node.nodeValue !== ORIGINAL_TEXT) node.nodeValue = ORIGINAL_TEXT;
      });
      state.currentPhrase = "";
      state.targets.clear();
    }

    /**
     * 取词库的显示名称。内置词库随界面语言切换，自定义词库用用户输入的原文。
     * 内置词库的字典 key 由 BUILTIN_NAME_KEYS 映射得到，映射表里查不到的按自定义词库处理。
     * @param {string} id 词库 id
     * @param {Function} t 翻译函数
     * @returns {string} 显示名称
     */
    function libraryName(id, t) {
      if (Object.prototype.hasOwnProperty.call(BUILTIN_NAME_KEYS, id)) return t(BUILTIN_NAME_KEYS[id]);
      var library = state.libraries[id];
      return (library && library.name) || id;
    }

    /**
     * 设置页面板：启停开关、词库切换、自定义词库增删。
     * t 由 slots 框架依据注册时声明的 locale 命名空间注入，随语言切换自动重渲染。
     * @param {Object} props 组件属性
     * @param {Function} props.t 当前语言的翻译函数
     * @returns {Object} React 元素
     */
    function LibrarySettings(props) {
      var t = props.t;
      var snap = React.useState(0), bump = snap[1];
      var rerender = function () { bump(function (value) { return value + 1; }); };
      var toggle = function (e) {
        state.enabled = e.target.checked;
        persist();
        restartSchedule();
        rerender();
      };
      var select = function (e) {
        state.libraryId = e.target.value;
        state.previous = "";
        state.sequenceIndex = 0;
        persist();
        restartSchedule();
        rerender();
      };
      var selectStrategy = function (e) {
        state.strategy = e.target.value;
        state.sequenceIndex = 0;
        persist();
        restartSchedule();
        rerender();
      };
      var add = function () {
        window.alert(t("createComingSoon"));
      };
      var remove = function () {
        if (isBuiltin(state.libraryId)) return;
        delete state.libraries[state.libraryId];
        state.libraryId = DEFAULT_ID;
        state.previous = "";
        state.sequenceIndex = 0;
        persist();
        restartSchedule();
        rerender();
      };
      installSettingsStyles();
      var count = ((state.libraries[state.libraryId] || {}).phrases || []).length;
      return h("section", { className: "dshTspSection" },
        h("div", { className: "dshTspCard" },
          h("header", { className: "dshTspHeader" },
            h("div", { className: "dshTspHeaderText" },
              h("div", { className: "dshTspTitle" }, t("title")),
              h("p", { className: "dshTspDescription" }, t("description"))
            )
          ),
          h("div", { className: "dshTspBody" },
            h("label", { className: "dshTspToggle", htmlFor: "dsh-tsp-enabled" },
              h("input", { id: "dsh-tsp-enabled", type: "checkbox", checked: state.enabled, onChange: toggle }),
              h("span", null, t("enable"))
            ),
            h("div", { className: "dshTspField" },
              h("label", { className: "dshTspLabel", htmlFor: "dsh-tsp-library" }, t("library")),
              h("select", { id: "dsh-tsp-library", className: "dshTspSelect", value: state.libraryId, onChange: select },
                Object.keys(state.libraries).map(function (id) { return h("option", { key: id, value: id }, libraryName(id, t)); })
              ),
              h("p", { className: "dshTspCount" }, t("count", { n: count })),
              h("div", { className: "dshTspContents" },
                h("label", { className: "dshTspLabel", htmlFor: "dsh-tsp-contents" }, t("contents")),
                h("textarea", {
                  id: "dsh-tsp-contents",
                  className: "dshTspTextarea",
                  value: ((state.libraries[state.libraryId] || {}).phrases || []).join("\n"),
                  readOnly: true,
                  spellCheck: false,
                  "aria-label": t("contents")
                })
              )
            ),
            h("div", { className: "dshTspField" },
              h("label", { className: "dshTspLabel", htmlFor: "dsh-tsp-strategy" }, t("strategy")),
              h("select", { id: "dsh-tsp-strategy", className: "dshTspSelect", value: state.strategy, onChange: selectStrategy },
                h("option", { value: STRATEGY_SEQUENTIAL }, t("strategySequential")),
                h("option", { value: STRATEGY_RANDOM }, t("strategyRandom")),
                h("option", { value: STRATEGY_WEIGHTED }, t("strategyWeighted"))
              )
            ),
            h("div", { className: "dshTspActions" },
              h("button", { className: "dshTspButton dshTspButtonPrimary", type: "button", onClick: add }, t("add")),
              !isBuiltin(state.libraryId) && h("button", { className: "dshTspButton dshTspButtonDanger", type: "button", onClick: remove }, t("remove"))
            )
          )
        )
      );
    }

    /**
     * 客户端插件入口：注册字典、读取配置、接管 turnStatus、注册设置页面板。
     * @param {Object} ctx 客户端插件上下文
     * @returns {void}
     */
    function apply(ctx) {
      installSettingsStyles();
      readState();
      start();
      ctx.effect(function () { return ctx.locale.register(NS, { zh: DICT_ZH, en: DICT_EN }); }, "turn-status-phrases: dictionaries");
      // 侧边导航标签不是组件，拿不到框架注入的 t，需自行绑定；label 是回调，渲染时按当前语言取值
      var translate = ctx.locale.bind(NS);
      ctx.slots.inject("settings.section", function () {
        return ctx.slots.register({
          name: "settings.section",
          id: "turn-status-phrases",
          order: 35,
          locale: NS,
          label: function () { return translate("title"); }
        }, LibrarySettings);
      });
      ctx.effect(function () { return function () { stop(); }; }, "turn-status-phrases: dom takeover");
    }

    var inject = ["slots", "locale"];
    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  }
});
