import { readFile, writeFile } from "node:fs/promises";
import { BUILTIN_LIBRARIES, DEFAULT_LIBRARY_ID } from "../lib/builtin-libraries/index.js";

const clientPath = new URL("../lib/client.js", import.meta.url);
const source = await readFile(clientPath, "utf8");
const builtins = JSON.stringify(BUILTIN_LIBRARIES, null, 2).replaceAll("\n", "\n    ");
const replacement = [
  "    // BUILTIN_LIBRARIES_START: generated by npm run build",
  "    var BUILTIN = " + builtins + ";",
  "    // BUILTIN_LIBRARIES_END"
].join("\n");

const builtinBlock = source.includes("// BUILTIN_LIBRARIES_START")
  ? /    \/\/ BUILTIN_LIBRARIES_START[\s\S]*?    \/\/ BUILTIN_LIBRARIES_END/
  : /    \/\/ 内置词库，与 lib\/phrases\.js 的 BUILTIN_LIBRARIES 保持一致\n    var BUILTIN = \{[\s\S]*?\n    \};/;
const next = source
  .replace(builtinBlock, replacement)
  .replace(/var DEFAULT_ID = "[^"]+";/, "var DEFAULT_ID = " + JSON.stringify(DEFAULT_LIBRARY_ID) + ";");

if (!source.includes("// BUILTIN_LIBRARIES_START") && next === source) {
  throw new Error("client library block is missing");
}
if (next !== source) await writeFile(clientPath, next);
